# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: https://raw.githubusercontent.com/EdutainmentLIVE/snapshot/89fc4cea3c905eb0c38923d5a1058ce5f9b27aed/snapshot.yaml
packages: []
