# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: https://raw.githubusercontent.com/EdutainmentLIVE/snapshot/3c01cf9ec72ef685706093e57a75284d131a668d/snapshot.yaml
packages: []
