# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: https://raw.githubusercontent.com/EdutainmentLIVE/snapshot/9ce60a6e8467d472f69adab756e57fe85845d406/snapshot.yaml
packages: []
